trigger:
- 'master'



variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    #pool:
    #  vmImage: 'ubuntu-20.04'
    #  demands:
    #  - npm
    pool:
      name: Default
      demands:
      - agent.name -equals agentdevops

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:
    - script: 'echo hello'
      displayName: 'Compile Sass assets'
